---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/manyobra/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp logo.png $DEPLOYPATH
    - /bin/cp sebastian.png $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp -R testimonios/ $DEPLOYPATH
