name: Deploy a cPanel

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Subir archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ftp.manyobra.cl
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            .cpanel.yml
            wordpress-theme/**
